// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYfMDbITbGOxwMbnKyZpmyjwAt3ifycHM',
    appId: '1:594860189403:web:676bbfc56990487f4e4efe',
    messagingSenderId: '594860189403',
    projectId: 'applaner-mae',
    authDomain: 'applaner-mae.firebaseapp.com',
    storageBucket: 'applaner-mae.firebasestorage.app',
    measurementId: 'G-BDTR598BHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4N8-huZKLrmkifPaXvzTzugEvZVAr6cM',
    appId: '1:594860189403:android:00b6ede3ad1b988b4e4efe',
    messagingSenderId: '594860189403',
    projectId: 'applaner-mae',
    storageBucket: 'applaner-mae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC31OuHppAJWQ-9ASQUbeTnR18ukT1MkH8',
    appId: '1:594860189403:ios:04bc1fec14dbe8f04e4efe',
    messagingSenderId: '594860189403',
    projectId: 'applaner-mae',
    storageBucket: 'applaner-mae.firebasestorage.app',
    iosBundleId: 'com.example.applanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC31OuHppAJWQ-9ASQUbeTnR18ukT1MkH8',
    appId: '1:594860189403:ios:04bc1fec14dbe8f04e4efe',
    messagingSenderId: '594860189403',
    projectId: 'applaner-mae',
    storageBucket: 'applaner-mae.firebasestorage.app',
    iosBundleId: 'com.example.applanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYfMDbITbGOxwMbnKyZpmyjwAt3ifycHM',
    appId: '1:594860189403:web:ff0ad438a2ae29e54e4efe',
    messagingSenderId: '594860189403',
    projectId: 'applaner-mae',
    authDomain: 'applaner-mae.firebaseapp.com',
    storageBucket: 'applaner-mae.firebasestorage.app',
    measurementId: 'G-198W7357DX',
  );

}